"use client";
import { useState } from "react";
import { motion, AnimatePresence } from "framer-motion";
import config from "@/lib/config";
import SectionReveal from "@/components/ui/SectionReveal";

function vietQRSrc(bank: string, account: string, holder: string) {
  // Lookup table for common Vietnamese bank short codes used by VietQR.
  const map: Record<string, string> = {
    vietcombank: "vcb",
    techcombank: "tcb",
    bidv: "bidv",
    vietinbank: "icb",
    mbbank: "mb",
    acb: "acb",
    sacombank: "stb",
    tpbank: "tpb",
    vpbank: "vpb",
    agribank: "vbarda",
  };
  const key = bank.toLowerCase().replace(/\s+/g, "");
  const code = map[key] ?? key;
  const url = `https://img.vietqr.io/image/${code}-${encodeURIComponent(
    account
  )}-compact2.png?accountName=${encodeURIComponent(holder)}`;
  return url;
}

export default function Gift() {
  const [open, setOpen] = useState(false);

  return (
    <section id="gift" className="relative px-6 py-12 text-center">
      <SectionReveal>
        <p className="mx-auto max-w-[380px] text-[13.5px] leading-relaxed text-[#7e4f4f]">
          {config.gifts.intro}
        </p>
      </SectionReveal>

      <SectionReveal delay={0.15}>
        <button
          onClick={() => setOpen(true)}
          className="mt-6 flex flex-col items-center mx-auto"
          aria-label={config.gifts.label}
        >
          {/* Stylised gift box */}
          <div className="float-gentle relative h-24 w-28">
            <div className="absolute inset-x-0 bottom-0 top-6 rounded-md bg-pink-200 shadow-md" />
            <div className="absolute inset-x-2 bottom-0 top-7 grid grid-cols-2 rounded-b-md">
              <div className="border-r-2 border-pink-100" />
            </div>
            <div className="absolute -top-1 inset-x-3 h-7 rounded bg-pink-300 shadow-sm" />
            <span className="absolute left-1/2 top-0 -translate-x-1/2 text-2xl text-rose-500">♡</span>
          </div>
          <span className="mt-3 font-cormorant tracking-widest text-[#cb6e6e]">
            {config.gifts.label}
          </span>
        </button>
      </SectionReveal>

      <AnimatePresence>
        {open && (
          <motion.div
            className="fixed inset-0 z-50 flex items-center justify-center bg-black/40 px-4"
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            exit={{ opacity: 0 }}
            onClick={() => setOpen(false)}
          >
            <motion.div
              initial={{ y: 30, scale: 0.96, opacity: 0 }}
              animate={{ y: 0, scale: 1, opacity: 1 }}
              exit={{ y: 20, scale: 0.96, opacity: 0 }}
              onClick={(e) => e.stopPropagation()}
              className="relative w-full max-w-sm rounded-lg bg-white p-5 shadow-2xl"
            >
              <button
                onClick={() => setOpen(false)}
                className="absolute right-3 top-3 text-2xl text-gray-400 hover:text-gray-700"
                aria-label="Đóng"
              >
                ×
              </button>
              <p className="text-center font-cormorant text-lg tracking-[0.2em] text-[#9c3e3e]">
                {config.gifts.label.toUpperCase()}
              </p>

              <div className="mt-4 grid grid-cols-1 gap-4">
                {config.gifts.accounts.map((a) => (
                  <div
                    key={a.accountNumber}
                    className="rounded border border-[#e9d4d4] p-3 text-center"
                  >
                    <p className="text-xs uppercase tracking-widest text-[#a95151]">
                      {a.side === "groom" ? "Chú rể" : "Cô dâu"}
                    </p>
                    <p className="mt-1 font-cormorant text-base">{a.bankName}</p>
                    <div className="mx-auto mt-2 h-32 w-32">
                      {/* Live QR generated by VietQR */}
                      {/* eslint-disable-next-line @next/next/no-img-element */}
                      <img
                        src={vietQRSrc(a.bankName, a.accountNumber, a.accountName)}
                        alt={`QR ${a.bankName}`}
                        className="h-full w-full object-contain"
                      />
                    </div>
                    <p className="mt-2 text-sm font-medium">{a.accountNumber}</p>
                    <p className="text-xs text-[#7e4f4f]">{a.accountName}</p>
                  </div>
                ))}
              </div>
            </motion.div>
          </motion.div>
        )}
      </AnimatePresence>
    </section>
  );
}
